[package]
name = "gameproject"
version = "0.0.0"
authors = [
    "Troels Sheepyhead Jessen <kairyuka@gmail.com>"
]

[[bin]]
name = "gameproject"

[dependencies]
piston = "0.49.0"
piston2d-graphics = "0.35.0"
pistoncore-glutin_window = "0.63.0"
piston2d-opengl_graphics = "0.69.0"